# Generated by Django 4.2 on 2025-03-24 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
    ]
